#!/bin/bash
#
# Daily breakthroughs chain:
#   1. Pull fresh RSS, score with Gemma, merge into data/breakthroughs.json
#   2. Regenerate the Codex/Claude orphan-seeding brief
#   3. Push to git so Vercel redeploys with the new feed
#   4. Notify via ntfy with the headline counts
#
# Triggered daily by ~/Library/LaunchAgents/com.healthuniverse.breakthroughs.daily.plist
# Logs append to /tmp/healthuniverse-breakthroughs.log
#
set -u
cd "$(dirname "$0")/.." || exit 1
REPO_ROOT="$(pwd)"

# ─── Config ───────────────────────────────────────────────────────
NTFY_TOPIC="${HU_NTFY_TOPIC:-aimon-gG9ITzfi4BNBklO3}"
PY="${REPO_ROOT}/.venv/bin/python"
[ -x "$PY" ] || PY="$(command -v python3)"

# ─── Helpers ──────────────────────────────────────────────────────
log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

ntfy() {
  local title="$1"; local body="$2"; local tag="${3:-test_tube}"
  if [ -z "$NTFY_TOPIC" ]; then return; fi
  curl -fsS -X POST "https://ntfy.sh/${NTFY_TOPIC}" \
    -H "Title: ${title}" -H "Tags: ${tag}" -H "Priority: default" \
    -d "${body}" >/dev/null 2>&1 || true
}

# ─── 1. Pull breakthroughs ────────────────────────────────────────
log "→ running breakthroughs_daily.py"
PRE_COUNT=$($PY -c "import json,sys; sys.path.insert(0,'.'); \
  d=json.load(open('data/breakthroughs.json')); print(len(d['items']))")

if ! $PY scripts/breakthroughs_daily.py 2>&1; then
  log "✗ daily ingest failed"
  ntfy "Health Universe breakthroughs: ingest FAILED" \
       "Check /tmp/healthuniverse-breakthroughs.log" "warning"
  exit 1
fi

POST_COUNT=$($PY -c "import json,sys; sys.path.insert(0,'.'); \
  d=json.load(open('data/breakthroughs.json')); print(len(d['items']))")
ADDED=$((POST_COUNT - PRE_COUNT))
log "→ items: ${PRE_COUNT} → ${POST_COUNT} (added ${ADDED})"

# ─── 2. Regenerate orphan brief ───────────────────────────────────
log "→ regenerating orphan brief"
BRIEF_OUT=$($PY scripts/orphans_to_brief.py 2>&1)
log "$BRIEF_OUT"
ORPHAN_COUNT=$(echo "$BRIEF_OUT" | sed -nE 's/.* ([0-9]+) candidates .*/\1/p' | head -1)
ORPHAN_COUNT="${ORPHAN_COUNT:-0}"

# ─── 3. Git push so Vercel redeploys ──────────────────────────────
if [ "$ADDED" -gt 0 ] || [ "$ORPHAN_COUNT" -gt 0 ]; then
  log "→ committing to git"
  cd "$REPO_ROOT" || exit 1
  git add data/breakthroughs.json briefs/ 2>/dev/null
  if git diff --cached --quiet; then
    log "  nothing to commit (already up to date)"
  else
    git -c user.email="breakthroughs-bot@healthuniverse.local" \
        -c user.name="Breakthroughs Bot" \
        commit -m "Daily breakthroughs: +${ADDED} items, ${ORPHAN_COUNT} orphans

Auto-generated by scripts/breakthroughs_chain.sh

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>" \
        >/dev/null && log "  committed"
    if git push origin HEAD 2>&1 | tail -3 | sed 's/^/    /'; then
      log "  pushed — Vercel will redeploy"
    else
      log "  ✗ push failed (continuing anyway)"
    fi
  fi
fi

# ─── 4. Notify ────────────────────────────────────────────────────
if [ "$ADDED" -gt 0 ]; then
  ntfy "Health Universe: +${ADDED} breakthrough$([ "$ADDED" -eq 1 ] || echo s)" \
"${ORPHAN_COUNT} orphan$([ "$ORPHAN_COUNT" -eq 1 ] || echo s) ready for Codex seeding.

https://healthuniverse.vercel.app/breakthroughs
https://healthuniverse.vercel.app/admin/breakthrough-orphans" "test_tube"
  log "→ ntfy sent"
elif [ "$ORPHAN_COUNT" -gt 5 ]; then
  ntfy "Health Universe: ${ORPHAN_COUNT} orphans backlog" \
"Codex seeding queue is growing. Brief at briefs/codex_orphans_$(date +%Y-%m-%d).md" "books"
  log "→ ntfy sent (backlog)"
else
  log "→ no changes, no notification"
fi

log "→ done"
